services:
  api:
    container_name: api
    build: .
    env_file: .env
    ports:
      - "8080:8080"
  mysql:
    container_name: db
    image: 'mysql:8.4'
    environment:
      - 'MYSQL_DATABASE=webapp'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_USER=myuser'
      - 'MYSQL_ROOT_PASSWORD=secret'
    ports:
      - '3306:3306'
  redis:
    container_name: cache
    image: 'redis:8.0-alpine'
    ports:
      - '6379:6379'
