#debug=true
spring.application.name=webapp

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# 30 minutes
spring.cache.redis.time-to-live=1800000

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://mysql:3306/webapp
spring.datasource.username=root
spring.datasource.password=secret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=false

email.fromName="Web App"
email.fromEmail=noreply@example.com

jwt.secret=${JWT_SECRET}
jwt.issuer=https://localhost
jwt.audience=demo

logging.level.root=INFO

mailgun.apikey=${MAILGUN_API_KEY}
mailgun.domain=${MAILGUN_DOMAIN}

pebble.suffix=.peb
pebble.cache=false
spring.thymeleaf.enabled=false
spring.freemarker.enabled=false
spring.groovy.template.enabled=false
